server:
  port: 8010
spring:
  application:
    name: discoveryservice
eureka:
  client:
    fetch-registry: false
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:8010/eureka
